### ISSUE TITLE
Tidy up message when volume defined in config already created

### ISSUE THREAD

**Issue by tobybellwood** [pygmystack/pygmy#125]
**Describe the bug**
With a custom config running that requires a volume (i.e. portainer as per #62), the message displayed on subsequent `up` calls could be improved - it contains malformed calls to map and references nil objects

> volumes:
>   portainer_data:
>     Name: portainer_data

**To Reproduce**
1. Use a custom config as per #62 
2. stop/restart pygmy-go
3. See misleading message below (not an error)

```
toby@MacBook-Pro pygmy-go % pygmy-go up --config ~/.demopygmy.yml  
Using config file: /Users/toby/.demopygmy.yml
Already created volume { map[]  portainer_data map[]  map[] <nil>}
```

**Expected behavior**
the message shouldn't contain all the `map[]`s and `<nil>`s.

**Comment by fubarhouse** [comment]
Thanks for submitting, I’ve got the changes already ready for committing locally 😊

Now there’s an issue so I can commit them!

**Comment by fubarhouse** [comment]
This is now merged - please re-test if you feel the need.
I'll close this (again) if it goes stale.
