### ISSUE TITLE
Update restart policies to match `on-fail` to remove `always`

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#184]
Long story short: containers shouldn't be present after a system reboot, and this has caused some issues for users. Note that this issue has been affecting some users in the original project.

* https://github.com/amazeeio/pygmy/issues/40

**Comment by tobybellwood** [comment]
yup - dnsmasq appears to be the main culprit for me!

**Comment by fubarhouse** [comment]
@tobybellwood, are you able to test the change on branch `issue/184` before it gets a PR?
