### ISSUE TITLE
Container Creation prevention in the event of specific errors.

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#25]
In the event containers have issues specifically with the name of the container _or_ the port number, we should in the event of container name _remove_ the container (but do not kill it), and in the event of port collision we should report on it.

After these checks have passed the containers would be allowed to start, however if they don't the application should close advising the user of the issues. Assuming the colliding container names are a problem, this shouldn't fail the application because the containers would be expected to be removed (but not killed).

So ideally port collision is the item which quits pygmy, and the user should be aware of it when they attempt to run pygmy.

**Comment by simesy** [comment]
I tested the issue/25 branch and the status stuff works well prior to starting pygmy. Unfortunately when i start pygmy I get:

```
$ pygmy-go up
Successfully pulled andyshinn/dnsmasq:2.78
Error response from daemon: driver failed programming external connectivity on endpoint amazeeio-dnsmasq (3880bef9e1ae8a758cdec9e19dbbe174491cfe13d567e7f0d2088e3989ff7480): Error starting userland proxy: listen tcp 0.0.0.0:6053: bind: address already in use
...
```

Confirmed that this is not an issue on HEAD.

**Comment by fubarhouse** [comment]
Notes:

* the additional functionality works as designed
* ~dnsmasq (port 53) is broken because of a change made upstream a while ago - portbinding needs to be updated.~ Not an issue if the environment is clean.
* container removal now targets the container ID - so that containers are removed regardless of their name (ie `/amazeeio-dnsmasq` vs `amazeeio-dnsmasq`). So, the logic doesn't care about the container name and will remove it regardless.

**Comment by simesy** [comment]
Looks great!
