### ISSUE TITLE
[feature] implement `stop` command

### ISSUE THREAD

**Issue by twardnw** [pygmystack/pygmy#288]
Currently the only option to stop the containers is with the `down` command, which removes _everything_related to Pygmy. While this is nice for cleanup, it is excessive. The Pygmy gem utilizes a `stop` command, which simply stops the containers. This command should be added to retain parity with the gem.

**Comment by fubarhouse** [comment]
Prioritizing this one - but similar was noted in #271

**Comment by fubarhouse** [comment]
Some questions about expected behavior:

* should the networks attempt to be removed when running this command?
* should the resolv configuration be removed when running this command?

**Comment by twardnw** [comment]
The current behavior in the gem version is to stop the containers (but not remove) and clean up the resolver. The network stays in place for `stop`

**Comment by fubarhouse** [comment]
There's now a test case which replicates the behavior in #271.
Once the issue is fixed and the test case passes this will be good for merging.
