### ISSUE TITLE
Arch-specific image support.

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#334]
Some sort of mechanism to use different images for different architectures would be ideal. Amazee.io are working on multi-architecture images and I am prepared for the fact this might be shipped as many images - so I'd like to stay ahead of that curve.

**Comment by tobybellwood** [comment]
My preference is to ship a single multi-arch image ref 😉, but good to have ability to configure image/tag easily

**Comment by fubarhouse** [comment]
Good to know - thanks. I simply wanted to have something functionally ready and working if the ability is so needed.

**Comment by tobybellwood** [comment]
Being able to override the images in config would make testing easier for sure!

**Comment by fubarhouse** [comment]
Technically, you already can. :wink: 

Having some options around which image to use on which architecture though... that's the intent. If this even gets merged then cool - I've no real opinion either way but it's an idea I'd like to explore. Even if it's just for a bit of personal fun.
