### ISSUE TITLE
Cheat-sheet of endpoints

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#55]
Users with pygmy running should be able to identify a set of endpoints which pygmy makes available. This will however be a manually controlled configuration item with some defaults.

```
endpoints:
  - mailhog.docker.amazee.io:1025
  - docker.amazee.io:80/stats
```

**Comment by tobybellwood** [comment]
Thanks! That's a really neat implementation, it works well, and is easy to customise yourself!
